export const racePresWinner = {
      "test": true,
      "id": "0",
      "office": "P",
      "eevp": 1,
      "type": "General",
      "level": "state",
      "state": "DC",
      "electoral": 3,
      "updated": 1603391865830,
      "reporting": 143,
      "precincts": 143,
      "reportingPercent": 1,
      "stateName": "District of Columbia",
      "stateAP": "D.C.",
      "rating": "likely-d",
      "called": true,
      "runoff": false,
      "winnerParty": "Dem",
      "candidates": [
        {
          "first": "Joe",
          "last": "Biden",
          "party": "Dem",
          "id": "1036",
          "votes": 287213,
          "avotes": 0,
          "electoral": 3,
          "winner": "X",
          "percent": 0.8438
        },
        {
          "first": "Jo",
          "last": "Jorgensen",
          "party": "Lib",
          "id": "67957",
          "votes": 30941,
          "avotes": 1,
          "electoral": 0,
          "percent": 0.0909
        },
        {
          "first": "Donald",
          "last": "Trump",
          "party": "GOP",
          "id": "8639",
          "votes": 13003,
          "avotes": 0,
          "electoral": 0,
          "incumbent": true,
          "percent": 0.0382
        },
        {
          "first": "",
          "last": "Other",
          "party": "Other",
          "id": "other-0",
          "votes": 9226,
          "avotes": 0,
          "electoral": 0,
          "count": 4,
          "percent": 0.0271
        }
      ],
      "president16": [
        {
          "last": "Clinton",
          "party": "Dem",
          "electoral": "3"
        }
      ],
      "previousParty": "Dem"
    };

export const countiesOneReporting = [
  {
    test: true,
    id: "0",
    office: "P",
    eevp: 0.43,
    type: "General",
    level: "county",
    state: "CA",
    fips: "06001",
    updated: 1603401128403,
    reporting: 575,
    precincts: 1014,
    reportingPercent: 0.5670611439842209,
    stateName: "California",
    stateAP: "Calif.",
    rating: "likely-d",
    called: true,
    runoff: false,
    winnerParty: "Dem",
    candidates: [
      {
        first: "Joe",
        last: "Biden",
        party: "Dem",
        id: "1036",
        votes: 296747,
        avotes: 1221,
        winner: "X",
        percent: 0.7958,
      },
      {
        first: "Donald",
        last: "Trump",
        party: "GOP",
        id: "8639",
        votes: 55350,
        avotes: 2548,
        incumbent: true,
        percent: 0.1484,
      },
      {
        first: "Gloria",
        last: "La Riva",
        party: "PFP",
        id: "7623",
        votes: 9020,
        avotes: 331,
        percent: 0.0242,
      },
      {
        first: "Roque",
        last: "De La Fuente",
        party: "AIP",
        id: "64542",
        votes: 4668,
        avotes: 124,
        percent: 0.0125,
      },
      {
        first: "Howie",
        last: "Hawkins",
        party: "Grn",
        id: "32916",
        votes: 3669,
        avotes: 73,
        percent: 0.0098,
      },
      {
        first: "Jo",
        last: "Jorgensen",
        party: "Lib",
        id: "67957",
        votes: 3436,
        avotes: 50,
        percent: 0.0092,
      },
    ],
    county: {
      past_margin: {
        party: "Dem",
        margin: 0.645821,
      },
      population: "1643700",
      race_total: "1643700",
      black_total: "177135",
      race_hispanic_total: "1643700",
      white_alone: "523391",
      hispanic_total: "369061",
      percent_bachelors: "0.46",
      median_income: "92574.0",
      percent_black: "0.10776601569629495",
      percent_white: "0.3184224615197421",
      percent_hispanic: "0.22453063211048244",
      unemployment: "0.028999999999999998",
      covid: null,
      countyName: "Alameda County",
    },
  },
  {
    test: true,
    id: "0",
    office: "P",
    eevp: 0.43,
    type: "General",
    level: "county",
    state: "CA",
    fips: "06003",
    updated: 1603401128403,
    reporting: 0,
    precincts: 5,
    reportingPercent: 0,
    stateName: "California",
    stateAP: "Calif.",
    rating: "likely-d",
    called: true,
    runoff: false,
    winnerParty: "Dem",
    candidates: [
      {
        first: "Joe",
        last: "Biden",
        party: "Dem",
        id: "1036",
        votes: 0,
        avotes: 0,
        winner: "X",
        percent: null,
      },
      {
        first: "Donald",
        last: "Trump",
        party: "GOP",
        id: "8639",
        votes: 0,
        avotes: 0,
        incumbent: true,
        percent: null,
      },
      {
        first: "Roque",
        last: "De La Fuente",
        party: "AIP",
        id: "64542",
        votes: 0,
        avotes: 0,
        percent: null,
      },
      {
        first: "Howie",
        last: "Hawkins",
        party: "Grn",
        id: "32916",
        votes: 0,
        avotes: 0,
        percent: null,
      },
      {
        first: "Jo",
        last: "Jorgensen",
        party: "Lib",
        id: "67957",
        votes: 0,
        avotes: 0,
        percent: null,
      },
      {
        first: "Gloria",
        last: "La Riva",
        party: "PFP",
        id: "7623",
        votes: 0,
        avotes: 0,
        percent: null,
      },
    ],
    county: {
      past_margin: {
        party: "Dem",
        margin: 0.195,
      },
      population: "1146",
      race_total: "1146",
      black_total: "9",
      race_hispanic_total: "1146",
      white_alone: "678",
      hispanic_total: "105",
      percent_bachelors: "0.3",
      median_income: "64688.0",
      percent_black: "0.007853403141361256",
      percent_white: "0.5916230366492147",
      percent_hispanic: "0.09162303664921466",
      unemployment: "0.051",
      covid: null,
      countyName: "Alpine County",
    },
  },
];
